Add docs for Reconciliation
Expensify/slate pull request #4
Opened 2016-11-23 21:35 UTC by yuwenmemon

Add docs for reconciliation. Copied everything over from the old doc: https://integrations.expensify.com/Integration-Server/doc/reconciliation.html

2016-11-24 00:08 UTC, francoisl requested changes

2016-11-24 00:08 UTC, francoisl commented on source/index.html.md
> +        "partnerUserID":"...",
the rest of the docs uses `_REPLACE` for consistency

2016-11-24 00:08 UTC, francoisl commented on source/index.html.md
> +| startDate | String | yyyy-mm-dd formatted date | The beginning date for which we will include expenses in the generated report.
nab: you don't need the `|` at the beginning

2016-11-24 00:08 UTC, francoisl commented on source/index.html.md
> +        <#list report.transactionList as transaction>
we should use `as expense` for consistency, that's how we called the expense in all the other templates from the start.

2016-11-28 19:41 UTC, yuwenmemon commented
Updated

2016-11-28 21:17 UTC, francoisl approved these changes

2016-11-28 21:17 UTC, merged